// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaPzzDFBT2pt-jU-GIR4e5QDh1X7efKG4',
    appId: '1:947319992288:web:d058c2579a3867b740c585',
    messagingSenderId: '947319992288',
    projectId: 'flutter-otp-rest-starter',
    authDomain: 'flutter-otp-rest-starter.firebaseapp.com',
    storageBucket: 'flutter-otp-rest-starter.firebasestorage.app',
    measurementId: 'G-T49BHVCTWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxFtENIFlYkoLk6nchuJmg5meP-84gJjs',
    appId: '1:947319992288:android:36d669db474ebfb340c585',
    messagingSenderId: '947319992288',
    projectId: 'flutter-otp-rest-starter',
    storageBucket: 'flutter-otp-rest-starter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh21MuSd9pwOqtn59XVclx47z007y_vz0',
    appId: '1:947319992288:ios:06dba0e0fc7efc9540c585',
    messagingSenderId: '947319992288',
    projectId: 'flutter-otp-rest-starter',
    storageBucket: 'flutter-otp-rest-starter.firebasestorage.app',
    iosBundleId: 'com.example.flutterOtpRestStarter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh21MuSd9pwOqtn59XVclx47z007y_vz0',
    appId: '1:947319992288:ios:06dba0e0fc7efc9540c585',
    messagingSenderId: '947319992288',
    projectId: 'flutter-otp-rest-starter',
    storageBucket: 'flutter-otp-rest-starter.firebasestorage.app',
    iosBundleId: 'com.example.flutterOtpRestStarter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaPzzDFBT2pt-jU-GIR4e5QDh1X7efKG4',
    appId: '1:947319992288:web:f0375d495fe1800540c585',
    messagingSenderId: '947319992288',
    projectId: 'flutter-otp-rest-starter',
    authDomain: 'flutter-otp-rest-starter.firebaseapp.com',
    storageBucket: 'flutter-otp-rest-starter.firebasestorage.app',
    measurementId: 'G-6P8MFV6GJP',
  );
}
